Fix the "show-deployments" command
Previously it would throw an error when you tried to run it, because
the format of "requested_by" was wrong:

Traceback (most recent call last):
  File "/usr/local/bin/weco-deploy", line 11, in <module>
    load_entry_point('weco-deploy', 'console_scripts', 'weco-deploy')()
  File "/Users/alexwlchan/repos/weco-deploy/src/deploy/deploy.py", line 350, in main
    cli()
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/alexwlchan/repos/weco-deploy/src/deploy/deploy.py", line 328, in show_deployments
    summaries = _summarise_release_deployments(releases)
  File "/Users/alexwlchan/repos/weco-deploy/src/deploy/deploy.py", line 313, in _summarise_release_deployments
    'requested_by': deployment.get('requested_by').split('/')[-1],
AttributeError: 'dict' object has no attribute 'split'