Remove an unused (and unspecified) param from release_deploy
Previously it would throw an error if you tried to run 'release-deploy':

    Traceback (most recent call last):
      File "/usr/local/bin/weco-deploy", line 11, in <module>
        load_entry_point('weco-deploy', 'console_scripts', 'weco-deploy')()
      File "/Users/alexwlchan/repos/weco-deploy/src/deploy/deploy.py", line 402, in main
        cli()
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/Users/alexwlchan/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 21, in new_func
        return f(get_current_context(), *args, **kwargs)
    TypeError: release_deploy() missing 1 required positional argument: 'namespace'

This argument is now passed around in the `ctx` object.